version: "3.9"

services:
  moviefinder:
    build: .
    ports:
      - "${APP_PORT:-5000}:5000"
    env_file:
      - .env
    environment:
      - omdb_api_key=${omdb_api_key}
      - APP_HOST=${APP_HOST:-0.0.0.0}
      - APP_PORT=${APP_PORT:-5000}
