name: Deploy Movie Finder

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose --version

      - name: Create .env file for Docker Compose
        run: |
          echo "omdb_api_key=${{ secrets.API_KEY }}" >> .env
          echo "APP_HOST=${{ secrets.APP_HOST }}" >> .env
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> .env

      - name: Run Docker Compose
        run: docker-compose up -d --build
